"""
CNN Training Script — Surgical Instrument Coating Monitor
Trains a MobileNetV2-based CNN to classify coating condition from images.

Usage:
    python cnn_training.py

Requirements:
    - data/image_paths.npy
    - data/image_labels.npy
    (generated by data_generation.py)

Output:
    - models/cnn_model.keras
    - data/cnn_probs_full.npy
    - data/cnn_labels_full.npy
"""

import os
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import tensorflow as tf
from PIL import Image
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.applications import MobileNetV2
from tensorflow.keras.applications.mobilenet_v2 import preprocess_input

# ─────────────────────────────────────────────
# PATHS
# ─────────────────────────────────────────────
DATA_DIR  = 'data'
MODEL_DIR = 'models'
os.makedirs(MODEL_DIR, exist_ok=True)

# ─────────────────────────────────────────────
# LOAD DATA
# ─────────────────────────────────────────────
print("Loading image data...")
image_paths = np.load(f'{DATA_DIR}/image_paths.npy')
labels      = np.load(f'{DATA_DIR}/image_labels.npy')

print(f"Images loaded : {len(image_paths)}")
print(f"Distribution  : {np.bincount(labels)}  [Good | Degraded | Failed]")

# ─────────────────────────────────────────────
# DATASET
# ─────────────────────────────────────────────
def load_and_preprocess_image(path, size=224):
    img = Image.open(path).convert('RGB').resize((size, size))
    return np.array(img, dtype=np.float32)


def build_image_dataset(paths, labels, batch_size=32, training=True):
    def load_image(path, label):
        img = tf.numpy_function(
            lambda p: load_and_preprocess_image(p.decode()),
            [path], tf.float32
        )
        img.set_shape([224, 224, 3])
        return img, label

    def augment(img, label):
        img = tf.image.random_flip_left_right(img)
        img = tf.image.random_flip_up_down(img)
        img = tf.image.random_brightness(img, max_delta=0.2)
        img = tf.image.random_contrast(img, 0.8, 1.2)
        return img, label

    ds = tf.data.Dataset.from_tensor_slices((paths, labels))
    ds = ds.map(load_image, num_parallel_calls=tf.data.AUTOTUNE)
    if training:
        ds = ds.map(augment, num_parallel_calls=tf.data.AUTOTUNE)
        ds = ds.shuffle(buffer_size=1000)
    return ds.batch(batch_size).prefetch(tf.data.AUTOTUNE)


idx = np.arange(len(labels))
train_idx, temp_idx = train_test_split(idx, test_size=0.3, stratify=labels, random_state=42)
val_idx, test_idx   = train_test_split(temp_idx, test_size=0.5, stratify=labels[temp_idx], random_state=42)

train_ds = build_image_dataset(image_paths[train_idx], labels[train_idx], batch_size=32, training=True)
val_ds   = build_image_dataset(image_paths[val_idx],   labels[val_idx],   batch_size=32, training=False)
test_ds  = build_image_dataset(image_paths[test_idx],  labels[test_idx],  batch_size=32, training=False)

print(f"Train: {len(train_idx)} | Val: {len(val_idx)} | Test: {len(test_idx)}")

# ─────────────────────────────────────────────
# MODEL
# ─────────────────────────────────────────────
def build_cnn_model(num_classes=3):
    base = MobileNetV2(
        input_shape=(224, 224, 3),
        include_top=False,
        weights='imagenet'
    )
    base.trainable = True
    for layer in base.layers[:-30]:
        layer.trainable = False

    data_augmentation = keras.Sequential([
        layers.RandomFlip("horizontal"),
        layers.RandomRotation(0.08),
        layers.RandomZoom(0.1),
        layers.RandomContrast(0.1),
    ])

    inputs  = keras.Input(shape=(224, 224, 3))
    x       = data_augmentation(inputs)
    x       = preprocess_input(x)
    x       = base(x, training=True)
    x       = layers.GlobalAveragePooling2D()(x)
    x       = layers.Dropout(0.5)(x)
    x       = layers.Dense(256, activation='relu')(x)
    x       = layers.Dropout(0.4)(x)
    outputs = layers.Dense(num_classes, activation='softmax')(x)

    model = keras.Model(inputs, outputs)
    model.compile(
        optimizer=keras.optimizers.Adam(1e-4),
        loss='sparse_categorical_crossentropy',
        metrics=['accuracy']
    )
    return model


cnn_model = build_cnn_model(num_classes=3)
cnn_model.summary()

# ─────────────────────────────────────────────
# TRAIN
# ─────────────────────────────────────────────
print("\nTraining CNN...")
callbacks = [
    keras.callbacks.ReduceLROnPlateau(
        monitor='val_loss', factor=0.5, patience=3, verbose=1
    ),
    keras.callbacks.EarlyStopping(
        monitor='val_loss', patience=4,
        restore_best_weights=True, verbose=1
    )
]

history = cnn_model.fit(
    train_ds,
    validation_data=val_ds,
    epochs=15,
    callbacks=callbacks
)

# ─────────────────────────────────────────────
# TRAINING CURVES
# ─────────────────────────────────────────────
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 4))
fig.suptitle('CNN Training', fontsize=14, fontweight='bold')

ax1.plot(history.history['loss'],     label='Train', color='#2196F3')
ax1.plot(history.history['val_loss'], label='Val',   color='#F44336')
ax1.set_title('Loss'); ax1.legend(); ax1.grid(True, alpha=0.3)

ax2.plot(history.history['accuracy'],     label='Train', color='#4CAF50')
ax2.plot(history.history['val_accuracy'], label='Val',   color='#FF9800')
ax2.set_title('Accuracy'); ax2.legend(); ax2.grid(True, alpha=0.3)

plt.tight_layout()
plt.savefig('cnn_training_curves.png', dpi=150)
plt.show()
print("Training curves saved to cnn_training_curves.png")

# ─────────────────────────────────────────────
# EVALUATE
# ─────────────────────────────────────────────
print("\nEvaluating on test set...")
cnn_probs_test = cnn_model.predict(test_ds, verbose=0)
y_pred = np.argmax(cnn_probs_test, axis=1)
y_true = labels[test_idx]

print("\n" + "="*50)
print("  CNN Test Results")
print("="*50)
print(classification_report(y_true, y_pred,
      target_names=['Good', 'Degraded', 'Failed']))

cm = confusion_matrix(y_true, y_pred)
fig, ax = plt.subplots(figsize=(7, 5))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=['Good', 'Degraded', 'Failed'],
            yticklabels=['Good', 'Degraded', 'Failed'], ax=ax)
ax.set_xlabel('Predicted'); ax.set_ylabel('True')
ax.set_title('CNN Confusion Matrix')
plt.tight_layout()
plt.savefig('cnn_confusion_matrix.png', dpi=150)
plt.show()
print("Confusion matrix saved to cnn_confusion_matrix.png")

# ─────────────────────────────────────────────
# SAVE MODEL + PROBABILITIES
# ─────────────────────────────────────────────
print("\nSaving model and probabilities...")
cnn_model.save(f'{MODEL_DIR}/cnn_model.keras')
print(f"Model saved to {MODEL_DIR}/cnn_model.keras")

image_paths_paired  = np.load(f'{DATA_DIR}/image_paths.npy')
image_labels_paired = np.load(f'{DATA_DIR}/image_labels.npy')

full_ds        = build_image_dataset(image_paths_paired, image_labels_paired, batch_size=64, training=False)
cnn_probs_full = cnn_model.predict(full_ds, verbose=1)

np.save(f'{DATA_DIR}/cnn_probs_full.npy',  cnn_probs_full)
np.save(f'{DATA_DIR}/cnn_labels_full.npy', image_labels_paired)

print(f"CNN probs shape    : {cnn_probs_full.shape}")
print(f"Label distribution : {np.bincount(image_labels_paired)}")
print("\nDone. Run lstm_training.py next.")