"""
Fusion Model Training Script - Surgical Instrument Coating Monitor
Trains an MLP fusion model on CNN + LSTM probability outputs.

Usage:
    python fusion_training.py

Requirements:
    - data/cnn_probs_full.npy
    - data/cnn_labels_full.npy
    - data/lstm_probs_full.npy
    - data/lstm_labels_full.npy
    (generated by cnn_training.py and lstm_training.py)

Output:
    - models/fusion_model.keras
"""

import os
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import tensorflow as tf
from collections import Counter
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.utils.class_weight import compute_class_weight
from tensorflow import keras
from tensorflow.keras import layers

# ─────────────────────────────────────────────
# PATHS
# ─────────────────────────────────────────────
DATA_DIR  = 'data'
MODEL_DIR = 'models'
os.makedirs(MODEL_DIR, exist_ok=True)

STATUS_LABELS = {0: 'All Clear', 1: 'Monitor', 2: 'Alert', 3: 'Critical'}

# ─────────────────────────────────────────────
# LOAD DATA
# ─────────────────────────────────────────────
print("Loading probabilities...")
cnn_probs   = np.load(f'{DATA_DIR}/cnn_probs_full.npy')
cnn_labels  = np.load(f'{DATA_DIR}/cnn_labels_full.npy')
lstm_probs  = np.load(f'{DATA_DIR}/lstm_probs_full.npy')
lstm_labels = np.load(f'{DATA_DIR}/lstm_labels_full.npy')

assert len(cnn_probs) == len(lstm_probs), \
    f"Size mismatch: CNN={len(cnn_probs)}, LSTM={len(lstm_probs)}"

n = len(cnn_probs)
print(f"Samples loaded         : {n}")
print(f"CNN label distribution : {np.bincount(cnn_labels)}")
print(f"LSTM label distribution: {np.bincount(lstm_labels)}")

# ─────────────────────────────────────────────
# FUSION LABEL LOGIC
# ─────────────────────────────────────────────
def derive_fusion_labels(cnn_labels, lstm_labels):
    labels = []
    for c, s in zip(cnn_labels, lstm_labels):
        c, s = int(c), int(s)
        if   c == 0 and s == 0: labels.append(0)
        elif c == 0 and s == 1: labels.append(1)
        elif c == 1 and s == 0: labels.append(1)
        elif c == 1 and s == 1: labels.append(1)
        elif c == 0 and s == 2: labels.append(2)
        elif c == 2 and s == 0: labels.append(2)
        elif c == 1 and s == 2: labels.append(3)
        elif c == 2 and s == 1: labels.append(3)
        elif c == 2 and s == 2: labels.append(3)
        else:                   labels.append(1)
    return np.array(labels)


fusion_all = derive_fusion_labels(cnn_labels, lstm_labels)
print("\nFusion label distribution:")
for label, count in sorted(Counter(fusion_all).items()):
    pct = count / len(fusion_all) * 100
    print(f"  {STATUS_LABELS[label]:12} : {count} ({pct:.1f}%)")

# ─────────────────────────────────────────────
# DATASET
# ─────────────────────────────────────────────
def build_fusion_dataset(cnn_p, lstm_p, cnn_l, lstm_l, batch_size=64, training=True):
    X = np.concatenate([cnn_p, lstm_p], axis=1).astype(np.float32)
    y = derive_fusion_labels(cnn_l, lstm_l).astype(np.int32)
    ds = tf.data.Dataset.from_tensor_slices((X, y))
    if training:
        ds = ds.shuffle(buffer_size=2000)
    return ds.batch(batch_size).prefetch(tf.data.AUTOTUNE), y


idx = np.arange(n)
train_idx, temp_idx = train_test_split(
    idx, test_size=0.3, stratify=fusion_all, random_state=42
)
val_idx, test_idx = train_test_split(
    temp_idx, test_size=0.5, stratify=fusion_all[temp_idx], random_state=42
)

train_ds, y_train = build_fusion_dataset(
    cnn_probs[train_idx], lstm_probs[train_idx],
    cnn_labels[train_idx], lstm_labels[train_idx], training=True
)
val_ds, y_val = build_fusion_dataset(
    cnn_probs[val_idx], lstm_probs[val_idx],
    cnn_labels[val_idx], lstm_labels[val_idx], training=False
)
test_ds, y_test = build_fusion_dataset(
    cnn_probs[test_idx], lstm_probs[test_idx],
    cnn_labels[test_idx], lstm_labels[test_idx], training=False
)

print(f"\nTrain: {len(train_idx)} | Val: {len(val_idx)} | Test: {len(test_idx)}")
print(f"Train label distribution : {np.bincount(y_train)}")
print(f"Val   label distribution : {np.bincount(y_val)}")
print(f"Test  label distribution : {np.bincount(y_test)}")

# ─────────────────────────────────────────────
# MODEL
# ─────────────────────────────────────────────
def build_fusion_model(input_size=6, num_classes=4):
    inputs  = keras.Input(shape=(input_size,))
    x       = layers.Dense(128, activation='relu')(inputs)
    x       = layers.Dropout(0.3)(x)
    x       = layers.Dense(64,  activation='relu')(x)
    x       = layers.Dropout(0.2)(x)
    x       = layers.Dense(32,  activation='relu')(x)
    x       = layers.Dropout(0.1)(x)
    x       = layers.Dense(16,  activation='relu')(x)
    outputs = layers.Dense(num_classes, activation='softmax')(x)
    model   = keras.Model(inputs, outputs)
    model.compile(
        optimizer=keras.optimizers.Adam(3e-4),
        loss='sparse_categorical_crossentropy',
        metrics=['accuracy']
    )
    return model


fusion_model = build_fusion_model()
fusion_model.summary()

# ─────────────────────────────────────────────
# TRAIN
# ─────────────────────────────────────────────
class_weights = compute_class_weight(
    class_weight='balanced',
    classes=np.unique(y_train),
    y=y_train
)
class_weight_dict = dict(enumerate(class_weights))

print("\nClass weights:")
for k, v in class_weight_dict.items():
    print(f"  {STATUS_LABELS[k]:12} : {v:.3f}")

print("\nTraining fusion model...")
history = fusion_model.fit(
    train_ds,
    validation_data=val_ds,
    epochs=40,
    class_weight=class_weight_dict
)

# ─────────────────────────────────────────────
# TRAINING CURVES
# ─────────────────────────────────────────────
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 4))
fig.suptitle('Fusion Model Training', fontsize=14, fontweight='bold')

ax1.plot(history.history['loss'],     label='Train', color='#2196F3')
ax1.plot(history.history['val_loss'], label='Val',   color='#F44336')
ax1.set_title('Loss'); ax1.legend(); ax1.grid(True, alpha=0.3)

ax2.plot(history.history['accuracy'],     label='Train', color='#4CAF50')
ax2.plot(history.history['val_accuracy'], label='Val',   color='#FF9800')
ax2.set_title('Accuracy'); ax2.legend(); ax2.grid(True, alpha=0.3)

plt.tight_layout()
plt.savefig('fusion_training_curves.png', dpi=150)
plt.show()
print("Training curves saved to fusion_training_curves.png")

# ─────────────────────────────────────────────
# EVALUATE
# ─────────────────────────────────────────────
print("\nEvaluating on test set...")
probs_test = fusion_model.predict(test_ds, verbose=0)
preds_test = np.argmax(probs_test, axis=1)

print("\n" + "="*50)
print("  Fusion Model Test Results")
print("="*50)
print(classification_report(y_test, preds_test,
      target_names=['All Clear', 'Monitor', 'Alert', 'Critical']))

cm = confusion_matrix(y_test, preds_test)
fig, ax = plt.subplots(figsize=(8, 6))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=['All Clear', 'Monitor', 'Alert', 'Critical'],
            yticklabels=['All Clear', 'Monitor', 'Alert', 'Critical'], ax=ax)
ax.set_xlabel('Predicted'); ax.set_ylabel('True')
ax.set_title('Fusion Confusion Matrix')
plt.tight_layout()
plt.savefig('fusion_confusion_matrix.png', dpi=150)
plt.show()
print("Confusion matrix saved to fusion_confusion_matrix.png")

# ─────────────────────────────────────────────
# SAVE MODEL
# ─────────────────────────────────────────────
fusion_model.save(f'{MODEL_DIR}/fusion_model.keras')
print(f"\nFusion model saved to {MODEL_DIR}/fusion_model.keras")
print("\nDone. All three models trained. Run app.py to launch the dashboard.")