"""
LSTM Training Script — Surgical Instrument Coating Monitor
Trains a Bidirectional LSTM to classify environmental sensor conditions.

Usage:
    python lstm_training.py

Requirements:
    - data/X_sensor.npy
    - data/y_sensor.npy
    (generated by data_generation.py)

Output:
    - models/lstm_model.keras
    - data/lstm_probs_full.npy
    - data/lstm_labels_full.npy
"""

import os
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix

# ─────────────────────────────────────────────
# PATHS
# ─────────────────────────────────────────────
DATA_DIR  = 'data'
MODEL_DIR = 'models'
os.makedirs(MODEL_DIR, exist_ok=True)

# ─────────────────────────────────────────────
# LOAD DATA
# ─────────────────────────────────────────────
print("Loading sensor data...")
X = np.load(f'{DATA_DIR}/X_sensor.npy')
y = np.load(f'{DATA_DIR}/y_sensor.npy')

print(f"X shape            : {X.shape}  [samples x timesteps x channels]")
print(f"Label distribution : {np.bincount(y)}  [Stable | Warning | Critical]")

# ─────────────────────────────────────────────
# DATASET
# ─────────────────────────────────────────────
def build_lstm_dataset(X, y, batch_size=64, training=True):
    ds = tf.data.Dataset.from_tensor_slices(
        (X.astype(np.float32), y.astype(np.int32))
    )
    if training:
        ds = ds.shuffle(buffer_size=2000)
    return ds.batch(batch_size).prefetch(tf.data.AUTOTUNE)


idx = np.arange(len(y))
train_idx, temp_idx = train_test_split(idx, test_size=0.3, stratify=y, random_state=42)
val_idx, test_idx   = train_test_split(temp_idx, test_size=0.5, stratify=y[temp_idx], random_state=42)

train_ds = build_lstm_dataset(X[train_idx], y[train_idx], training=True)
val_ds   = build_lstm_dataset(X[val_idx],   y[val_idx],   training=False)
test_ds  = build_lstm_dataset(X[test_idx],  y[test_idx],  training=False)

print(f"Train: {len(train_idx)} | Val: {len(val_idx)} | Test: {len(test_idx)}")

# ─────────────────────────────────────────────
# MODEL
# ─────────────────────────────────────────────
def build_lstm_model(input_size=5, hidden_size=64, num_classes=3):
    inputs = keras.Input(shape=(None, input_size))
    x = layers.Bidirectional(
        layers.LSTM(hidden_size, return_sequences=True, dropout=0.2)
    )(inputs)
    x = layers.Bidirectional(
        layers.LSTM(hidden_size, return_sequences=False, dropout=0.2)
    )(x)
    x       = layers.Dense(64, activation='relu')(x)
    x       = layers.Dropout(0.2)(x)
    outputs = layers.Dense(num_classes, activation='softmax')(x)
    model   = keras.Model(inputs, outputs)
    model.compile(
        optimizer=keras.optimizers.Adam(1e-3),
        loss='sparse_categorical_crossentropy',
        metrics=['accuracy']
    )
    return model


lstm_model = build_lstm_model(input_size=5, hidden_size=64, num_classes=3)
lstm_model.summary()

# ─────────────────────────────────────────────
# TRAIN
# ─────────────────────────────────────────────
print("\nTraining LSTM...")
callbacks = [
    keras.callbacks.ReduceLROnPlateau(
        monitor='val_loss', factor=0.5, patience=2, verbose=1
    ),
    keras.callbacks.EarlyStopping(
        monitor='val_loss', patience=3,
        restore_best_weights=True, verbose=1
    )
]

history = lstm_model.fit(
    train_ds,
    validation_data=val_ds,
    epochs=15,
    callbacks=callbacks
)

# ─────────────────────────────────────────────
# TRAINING CURVES
# ─────────────────────────────────────────────
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 4))
fig.suptitle('LSTM Training', fontsize=14, fontweight='bold')

ax1.plot(history.history['loss'],     label='Train', color='#2196F3')
ax1.plot(history.history['val_loss'], label='Val',   color='#F44336')
ax1.set_title('Loss'); ax1.legend(); ax1.grid(True, alpha=0.3)

ax2.plot(history.history['accuracy'],     label='Train', color='#4CAF50')
ax2.plot(history.history['val_accuracy'], label='Val',   color='#FF9800')
ax2.set_title('Accuracy'); ax2.legend(); ax2.grid(True, alpha=0.3)

plt.tight_layout()
plt.savefig('lstm_training_curves.png', dpi=150)
plt.show()
print("Training curves saved to lstm_training_curves.png")

# ─────────────────────────────────────────────
# EVALUATE
# ─────────────────────────────────────────────
print("\nEvaluating on test set...")
lstm_probs_test = lstm_model.predict(test_ds, verbose=0)
y_pred = np.argmax(lstm_probs_test, axis=1)
y_true = y[test_idx]

print("\n" + "="*50)
print("  LSTM Test Results")
print("="*50)
print(classification_report(y_true, y_pred,
      target_names=['Stable', 'Warning', 'Critical']))

cm = confusion_matrix(y_true, y_pred)
fig, ax = plt.subplots(figsize=(7, 5))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=['Stable', 'Warning', 'Critical'],
            yticklabels=['Stable', 'Warning', 'Critical'], ax=ax)
ax.set_xlabel('Predicted'); ax.set_ylabel('True')
ax.set_title('LSTM Confusion Matrix')
plt.tight_layout()
plt.savefig('lstm_confusion_matrix.png', dpi=150)
plt.show()
print("Confusion matrix saved to lstm_confusion_matrix.png")

# ─────────────────────────────────────────────
# SAVE MODEL + PROBABILITIES
# ─────────────────────────────────────────────
print("\nSaving model and probabilities...")
lstm_model.save(f'{MODEL_DIR}/lstm_model.keras')
print(f"Model saved to {MODEL_DIR}/lstm_model.keras")

full_ds         = build_lstm_dataset(X, y, batch_size=64, training=False)
lstm_probs_full = lstm_model.predict(full_ds, verbose=1)

np.save(f'{DATA_DIR}/lstm_probs_full.npy',  lstm_probs_full)
np.save(f'{DATA_DIR}/lstm_labels_full.npy', y)

print(f"LSTM probs shape   : {lstm_probs_full.shape}")
print(f"Label distribution : {np.bincount(y)}")
print("\nDone. Run fusion_training.py next.")